#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 22 17:25:07 2018

@author: travisbarton
"""

reddit = praw.Reddit(user_agent='Comment Extraction (by /u/USERNAME)',
                     client_id='bepL4c1oHsSEIA', client_secret='Mj6pnYQS1QB6Vh1Fyt1cXSb1EF8',
                     username=base64.b64decode('RHJpbGxTYXJnZW50Qm90'), 
                     password=(base64.b64decode("SUxvdmVMaW5kc2V5MTIz")))


for msg in reddit.inbox.stream(skip_existing = True):
    print('hello')
    if msg == 'all':
        all_repots()
    else:
        report(msg)
    

